"""login is not nullable

Revision ID: 105c1c44ff70
Revises: 2003c675a267
Create Date: 2013-12-09 10:52:50.646000

"""

# revision identifiers, used by Alembic.
revision = '105c1c44ff70'
down_revision = '2003c675a267'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('labmanager_users', 'login',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('labmanager_users', 'login',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    ### end Alembic commands ###
