"""Add more columns to EmbedApplication

Revision ID: 13f9fd64f85b
Revises: 47124d1df386
Create Date: 2016-11-04 00:05:59.223362

"""

# revision identifiers, used by Alembic.
revision = '13f9fd64f85b'
down_revision = '47124d1df386'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EmbedApplications', sa.Column('age_ranges_commas', sa.Unicode(length=100), nullable=True))
    op.add_column('EmbedApplications', sa.Column('description', sa.UnicodeText(), nullable=True))
    op.add_column('EmbedApplications', sa.Column('domains_json', sa.Unicode(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('EmbedApplications', 'domains_json')
    op.drop_column('EmbedApplications', 'description')
    op.drop_column('EmbedApplications', 'age_ranges_commas')
    ### end Alembic commands ###
