"""embed linked to siway users

Revision ID: 1545f86081cd
Revises: 37d7a02ce519
Create Date: 2016-11-03 09:46:39.751143

"""

# revision identifiers, used by Alembic.
revision = '1545f86081cd'
down_revision = '37d7a02ce519'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
