"""SiWaySAMLUser completed

Revision ID: 184b1606a9dc
Revises: 2c4a51c0e9ff
Create Date: 2016-10-28 10:29:51.989084

"""

# revision identifiers, used by Alembic.
revision = '184b1606a9dc'
down_revision = '2c4a51c0e9ff'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SiWaySAMLUsers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Unicode(length=255), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('employee_type', sa.Unicode(length=255), nullable=False),
    sa.Column('full_name', sa.Unicode(length=255), nullable=False),
    sa.Column('short_name', sa.Unicode(length=255), nullable=False),
    sa.Column('school_name', sa.Unicode(length=255), nullable=False),
    sa.Column('group', sa.Unicode(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_SiWaySAMLUsers_email', 'SiWaySAMLUsers', ['email'], unique=True)
    op.drop_table(u'GoLabOAuthUsers')
    op.drop_index(u'ix_labmanager_users_name', table_name='labmanager_users')
    op.drop_index(u'ix_labmanager_users_password', table_name='labmanager_users')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(u'ix_labmanager_users_password', 'labmanager_users', [u'password'], unique=False)
    op.create_index(u'ix_labmanager_users_name', 'labmanager_users', [u'name'], unique=False)
    op.create_table(u'GoLabOAuthUsers',
    sa.Column(u'id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column(u'display_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column(u'email', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint(u'id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_index(u'ix_SiWaySAMLUsers_email', table_name='SiWaySAMLUsers')
    op.drop_table('SiWaySAMLUsers')
    ### end Alembic commands ###
