"""labUser change

Revision ID: 1997f106f707
Revises: 26909b70f894
Create Date: 2016-10-24 11:54:59.038338

"""

# revision identifiers, used by Alembic.
revision = '1997f106f707'
down_revision = '26909b70f894'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(u'ix_labmanager_users_login', 'labmanager_users', ['login'], unique=True)
    op.create_index(u'ix_labmanager_users_name', 'labmanager_users', ['name'], unique=False)
    op.create_index(u'ix_labmanager_users_password', 'labmanager_users', ['password'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_labmanager_users_password', table_name='labmanager_users')
    op.drop_index(u'ix_labmanager_users_name', table_name='labmanager_users')
    op.drop_index(u'ix_labmanager_users_login', table_name='labmanager_users')
    ### end Alembic commands ###
