"""Integrating embed tables

Revision ID: 1b8856078bd3
Revises: f2b0984f780
Create Date: 2016-10-28 10:58:42.229165

"""

# revision identifiers, used by Alembic.
revision = '1b8856078bd3'
down_revision = 'f2b0984f780'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SiWaySAMLUsers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Unicode(length=255), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('employee_type', sa.Unicode(length=255), nullable=False),
    sa.Column('full_name', sa.Unicode(length=255), nullable=False),
    sa.Column('short_name', sa.Unicode(length=255), nullable=False),
    sa.Column('school_name', sa.Unicode(length=255), nullable=False),
    sa.Column('group', sa.Unicode(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_SiWaySAMLUsers_email', 'SiWaySAMLUsers', ['email'], unique=True)
    op.create_table('EmbedApplications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Unicode(length=255), nullable=False),
    sa.Column('name', sa.Unicode(length=100), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('scale', sa.Integer(), nullable=True),
    sa.Column('identifier', sa.Unicode(length=36), nullable=False),
    sa.Column('creation', sa.DateTime(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['lt_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_EmbedApplications_creation', 'EmbedApplications', ['creation'], unique=False)
    op.create_index(u'ix_EmbedApplications_identifier', 'EmbedApplications', ['identifier'], unique=True)
    op.create_index(u'ix_EmbedApplications_last_update', 'EmbedApplications', ['last_update'], unique=False)
    op.create_index(u'ix_EmbedApplications_name', 'EmbedApplications', ['name'], unique=False)
    op.create_index(u'ix_EmbedApplications_url', 'EmbedApplications', ['url'], unique=False)
    op.create_table('EmbedApplicationTranslation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('embed_application_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.Unicode(length=255), nullable=False),
    sa.Column('language', sa.Unicode(length=10), nullable=False),
    sa.ForeignKeyConstraint(['embed_application_id'], ['EmbedApplications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_EmbedApplicationTranslation_language', 'EmbedApplicationTranslation', ['language'], unique=False)
    op.create_index(u'ix_EmbedApplicationTranslation_url', 'EmbedApplicationTranslation', ['url'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_EmbedApplicationTranslation_url', table_name='EmbedApplicationTranslation')
    op.drop_index(u'ix_EmbedApplicationTranslation_language', table_name='EmbedApplicationTranslation')
    op.drop_table('EmbedApplicationTranslation')
    op.drop_index(u'ix_EmbedApplications_url', table_name='EmbedApplications')
    op.drop_index(u'ix_EmbedApplications_name', table_name='EmbedApplications')
    op.drop_index(u'ix_EmbedApplications_last_update', table_name='EmbedApplications')
    op.drop_index(u'ix_EmbedApplications_identifier', table_name='EmbedApplications')
    op.drop_index(u'ix_EmbedApplications_creation', table_name='EmbedApplications')
    op.drop_table('EmbedApplications')
    op.drop_index(u'ix_SiWaySAMLUsers_email', table_name='SiWaySAMLUsers')
    op.drop_table('SiWaySAMLUsers')
    ### end Alembic commands ###
