"""Add publicly available to RLMS

Revision ID: 1c131a5ca91f
Revises: 551dcad9db25
Create Date: 2014-07-28 20:33:20.872771

"""

# revision identifiers, used by Alembic.
revision = '1c131a5ca91f'
down_revision = 'c1a931faf5f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rlmss', sa.Column('public_identifier', sa.Unicode(length=50), nullable=False))
    op.add_column('rlmss', sa.Column('publicly_available', sa.Boolean(), nullable=False))
    op.create_index('ix_rlmss_publicly_available', 'rlmss', ['publicly_available'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rlmss_publicly_available', table_name='rlmss')
    op.drop_column('rlmss', 'publicly_available')
    op.drop_column('rlmss', 'public_identifier')
    ### end Alembic commands ###
