"""Add public_availability

Revision ID: 2003c675a267
Revises: 46a3d679666e
Create Date: 2013-10-09 00:09:21.484225

"""

# revision identifiers, used by Alembic.
revision = '2003c675a267'
down_revision = '46a3d679666e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laboratories', sa.Column('public_identifier', sa.Unicode(length=50), nullable=False))
    op.add_column('laboratories', sa.Column('publicly_available', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('laboratories', 'publicly_available')
    op.drop_column('laboratories', 'public_identifier')
    ### end Alembic commands ###
