"""Add public_availability for laboratories, and validated and completed for rlms

Revision ID: 2003c675a267
Revises: 46a3d679666e
Create Date: 2013-10-09 00:09:21.484225

"""

# revision identifiers, used by Alembic.
revision = '2003c675a267'
down_revision = '46a3d679666e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laboratories', sa.Column('public_identifier', sa.Unicode(length=50), nullable=False))
    op.add_column('laboratories', sa.Column('publicly_available', sa.Boolean(), nullable=False))
    op.add_column('rlmss', sa.Column('validated', sa.Boolean(), nullable=False))
#    op.add_column('rlmss', sa.Column('completed', sa.Boolean(), nullable=False))
    op.add_column('rlmss', sa.Column('newrlms', sa.Boolean(), nullable=False))

    op.create_table('http_rlms_property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rlms_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=50), nullable=False),
    sa.Column('value', sa.Unicode(length=50), nullable=False),
    sa.ForeignKeyConstraint(['rlms_id'], ['rlmss.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name','rlms_id')
    )
    
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('laboratories', 'publicly_available')
    op.drop_column('laboratories', 'public_identifier')
    op.drop_column('rlmss', 'validated')
#    op.drop_column('rlmss', 'completed')
    op.drop_column('rlmss', 'newrlms')

    op.drop_table('http_rlms_property')
    ### end Alembic commands ###
