"""Add new table for RLMS-level cache

Revision ID: 229fd8d6f159
Revises: 1a3e5ec9c2fd
Create Date: 2015-05-07 09:29:51.133081

"""

# revision identifiers, used by Alembic.
revision = '229fd8d6f159'
down_revision = '1a3e5ec9c2fd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rlms_caches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rlms_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Unicode(length=255), nullable=True),
    sa.Column('value', sa.UnicodeText(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rlms_id'], ['rlmss.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_rlms_caches_datetime', 'rlms_caches', ['datetime'], unique=False)
    op.create_index(u'ix_rlms_caches_key', 'rlms_caches', ['key'], unique=False)
    op.create_index(u'ix_rlmstype_cache_datetime', 'rlmstype_cache', ['datetime'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_rlmstype_cache_datetime', table_name='rlmstype_cache')
    op.drop_index(u'ix_rlms_caches_key', table_name='rlms_caches')
    op.drop_index(u'ix_rlms_caches_datetime', table_name='rlms_caches')
    op.drop_table('rlms_caches')
    ### end Alembic commands ###
