"""Added EmbedApplication etc

Revision ID: 26909b70f894
Revises: 5623247d3b03
Create Date: 2016-10-24 11:44:59.400638

"""

# revision identifiers, used by Alembic.
revision = '26909b70f894'
down_revision = '5623247d3b03'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'EmbedApplications_ibfk_1', 'EmbedApplications', type_='foreignkey')
    op.create_foreign_key(None, 'EmbedApplications', 'labmanager_users', ['owner_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'EmbedApplications', type_='foreignkey')
    op.create_foreign_key(u'EmbedApplications_ibfk_1', 'EmbedApplications', u'GoLabOAuthUsers', [u'owner_id'], [u'id'])
    ### end Alembic commands ###
