"""Add LocationCache

Revision ID: 292d93c545f2
Revises: 17d2927a8743
Create Date: 2017-06-09 18:40:25.576169

"""

# revision identifiers, used by Alembic.
revision = '292d93c545f2'
down_revision = '17d2927a8743'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LocationCache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pack', sa.Unicode(length=255), nullable=False),
    sa.Column('lookup_time', sa.DateTime(), nullable=False),
    sa.Column('hostname', sa.Unicode(length=255), nullable=True),
    sa.Column('city', sa.Unicode(length=255), nullable=True),
    sa.Column('country', sa.Unicode(length=255), nullable=True),
    sa.Column('most_specific_subdivision', sa.Unicode(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_LocationCache_city', 'LocationCache', ['city'], unique=False)
    op.create_index(u'ix_LocationCache_country', 'LocationCache', ['country'], unique=False)
    op.create_index(u'ix_LocationCache_hostname', 'LocationCache', ['hostname'], unique=False)
    op.create_index(u'ix_LocationCache_lookup_time', 'LocationCache', ['lookup_time'], unique=False)
    op.create_index(u'ix_LocationCache_most_specific_subdivision', 'LocationCache', ['most_specific_subdivision'], unique=False)
    op.create_index(u'ix_LocationCache_pack', 'LocationCache', ['pack'], unique=False)
    op.add_column(u'UseLogs', sa.Column('city', sa.Unicode(length=255), nullable=True))
    op.add_column(u'UseLogs', sa.Column('country', sa.Unicode(length=255), nullable=True))
    op.add_column(u'UseLogs', sa.Column('hostname', sa.Unicode(length=255), nullable=True))
    op.create_index(u'ix_UseLogs_city', 'UseLogs', ['city'], unique=False)
    op.create_index(u'ix_UseLogs_country', 'UseLogs', ['country'], unique=False)
    op.create_index(u'ix_UseLogs_hostname', 'UseLogs', ['hostname'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_UseLogs_hostname', table_name='UseLogs')
    op.drop_index(u'ix_UseLogs_country', table_name='UseLogs')
    op.drop_index(u'ix_UseLogs_city', table_name='UseLogs')
    op.drop_column(u'UseLogs', 'hostname')
    op.drop_column(u'UseLogs', 'country')
    op.drop_column(u'UseLogs', 'city')
    op.drop_index(u'ix_LocationCache_pack', table_name='LocationCache')
    op.drop_index(u'ix_LocationCache_most_specific_subdivision', table_name='LocationCache')
    op.drop_index(u'ix_LocationCache_lookup_time', table_name='LocationCache')
    op.drop_index(u'ix_LocationCache_hostname', table_name='LocationCache')
    op.drop_index(u'ix_LocationCache_country', table_name='LocationCache')
    op.drop_index(u'ix_LocationCache_city', table_name='LocationCache')
    op.drop_table('LocationCache')
    ### end Alembic commands ###
