"""Add name to RLMS

Revision ID: 298c12227419
Revises: 229fd8d6f159
Create Date: 2015-05-08 13:50:33.747142

"""

# revision identifiers, used by Alembic.
revision = '298c12227419'
down_revision = '229fd8d6f159'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('laboratories', 'laboratory_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('laboratories', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.add_column('rlmss', sa.Column('name', sa.Unicode(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rlmss', 'name')
    op.alter_column('laboratories', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('laboratories', 'laboratory_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    ### end Alembic commands ###
