"""Add languages

Revision ID: 2b963e6ca2a2
Revises: 3aac2c8dbcb6
Create Date: 2017-06-11 19:01:30.554383

"""

# revision identifiers, used by Alembic.
revision = '2b963e6ca2a2'
down_revision = '3aac2c8dbcb6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UseLogs', sa.Column('all_languages', sa.Unicode(length=100), nullable=True))
    op.add_column('UseLogs', sa.Column('first_language', sa.Unicode(length=10), nullable=True))
    op.add_column('UseLogs', sa.Column('second_language', sa.Unicode(length=10), nullable=True))
    op.add_column('UseLogs', sa.Column('third_language', sa.Unicode(length=10), nullable=True))
    op.create_index(u'ix_UseLogs_all_languages', 'UseLogs', ['all_languages'], unique=False)
    op.create_index(u'ix_UseLogs_first_language', 'UseLogs', ['first_language'], unique=False)
    op.create_index(u'ix_UseLogs_second_language', 'UseLogs', ['second_language'], unique=False)
    op.create_index(u'ix_UseLogs_third_language', 'UseLogs', ['third_language'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_UseLogs_third_language', table_name='UseLogs')
    op.drop_index(u'ix_UseLogs_second_language', table_name='UseLogs')
    op.drop_index(u'ix_UseLogs_first_language', table_name='UseLogs')
    op.drop_index(u'ix_UseLogs_all_languages', table_name='UseLogs')
    op.drop_column('UseLogs', 'third_language')
    op.drop_column('UseLogs', 'second_language')
    op.drop_column('UseLogs', 'first_language')
    op.drop_column('UseLogs', 'all_languages')
    ### end Alembic commands ###
