"""ltUser change

Revision ID: 2c4a51c0e9ff
Revises: 1997f106f707
Create Date: 2016-10-24 12:01:52.335632

"""

# revision identifiers, used by Alembic.
revision = '2c4a51c0e9ff'
down_revision = '1997f106f707'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'EmbedApplications_ibfk_1', 'EmbedApplications', type_='foreignkey')
    op.create_foreign_key(None, 'EmbedApplications', 'lt_users', ['owner_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'EmbedApplications', type_='foreignkey')
    op.create_foreign_key(u'EmbedApplications_ibfk_1', 'EmbedApplications', u'labmanager_users', [u'owner_id'], [u'id'])
    ### end Alembic commands ###
