"""Add owner back

Revision ID: 31d0762f6afc
Revises: 49b367d3d25f
Create Date: 2017-04-07 01:12:51.324832

"""

# revision identifiers, used by Alembic.
revision = '31d0762f6afc'
down_revision = '49b367d3d25f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EmbedApplications', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'EmbedApplications', 'GoLabOAuthUsers', ['owner_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'EmbedApplications', type_='foreignkey')
    op.drop_column('EmbedApplications', 'owner_id')
    ### end Alembic commands ###
