"""user password added to SiWaySAMLUsers table

Revision ID: 37d7a02ce519
Revises: 1b8856078bd3
Create Date: 2016-10-28 11:41:48.639806

"""

# revision identifiers, used by Alembic.
revision = '37d7a02ce519'
down_revision = '1b8856078bd3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
