"""UnicodeText has a limit of 64K in MySQL. Increase

Revision ID: 37e42fa9d88e
Revises: e657e849733
Create Date: 2015-06-03 19:15:24.676821

"""

# revision identifiers, used by Alembic.
revision = '37e42fa9d88e'
down_revision = 'e657e849733'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rlmstype_cache', 'value', type_ = sa.UnicodeText(512 * 1024 * 1024))
    op.alter_column('rlms_caches', 'value', type_ = sa.UnicodeText(512 * 1024 * 1024))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
