"""Add admin for golab users

Revision ID: 392aa82bba8f
Revises: 31d0762f6afc
Create Date: 2017-04-09 00:04:37.639719

"""

# revision identifiers, used by Alembic.
revision = '392aa82bba8f'
down_revision = '31d0762f6afc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('GoLabOAuthUsers', sa.Column('admin', sa.Boolean(), nullable=True))
    op.create_index(u'ix_GoLabOAuthUsers_admin', 'GoLabOAuthUsers', ['admin'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_GoLabOAuthUsers_admin', table_name='GoLabOAuthUsers')
    op.drop_column('GoLabOAuthUsers', 'admin')
    ### end Alembic commands ###
