"""Add browser info

Revision ID: 3999a40ec7b
Revises: 292d93c545f2
Create Date: 2017-06-09 18:53:32.305876

"""

# revision identifiers, used by Alembic.
revision = '3999a40ec7b'
down_revision = '292d93c545f2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UseLogs', sa.Column('browser_language', sa.Unicode(length=100), nullable=True))
    op.add_column('UseLogs', sa.Column('browser_name', sa.Unicode(length=100), nullable=True))
    op.add_column('UseLogs', sa.Column('browser_platform', sa.Unicode(length=100), nullable=True))
    op.add_column('UseLogs', sa.Column('browser_version', sa.Unicode(length=100), nullable=True))
    op.create_index(u'ix_UseLogs_browser_language', 'UseLogs', ['browser_language'], unique=False)
    op.create_index(u'ix_UseLogs_browser_name', 'UseLogs', ['browser_name'], unique=False)
    op.create_index(u'ix_UseLogs_browser_platform', 'UseLogs', ['browser_platform'], unique=False)
    op.create_index(u'ix_UseLogs_browser_version', 'UseLogs', ['browser_version'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_UseLogs_browser_version', table_name='UseLogs')
    op.drop_index(u'ix_UseLogs_browser_platform', table_name='UseLogs')
    op.drop_index(u'ix_UseLogs_browser_name', table_name='UseLogs')
    op.drop_index(u'ix_UseLogs_browser_language', table_name='UseLogs')
    op.drop_column('UseLogs', 'browser_version')
    op.drop_column('UseLogs', 'browser_platform')
    op.drop_column('UseLogs', 'browser_name')
    op.drop_column('UseLogs', 'browser_language')
    ### end Alembic commands ###
