"""Remove password

Revision ID: 47124d1df386
Revises: 1545f86081cd
Create Date: 2016-11-03 17:12:14.046930

"""

# revision identifiers, used by Alembic.
revision = '47124d1df386'
down_revision = '1545f86081cd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_column('siway_user', u'password')
    except:
        pass
    ### end Alembic commands ###
    pass


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    try:
        op.add_column('siway_user', sa.Column(u'password', mysql.VARCHAR(length=255), nullable=False))
    except:
        pass
    ### end Alembic commands ###
