"""Add missing indexes

Revision ID: 4bc4c1ae0f38
Revises: 105c1c44ff70
Create Date: 2014-04-29 21:28:23.149125

"""

# revision identifiers, used by Alembic.
revision = '4bc4c1ae0f38'
down_revision = '105c1c44ff70'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_laboratories_available', 'laboratories', ['available'], unique=False)
    op.create_index('ix_laboratories_publicly_available', 'laboratories', ['publicly_available'], unique=False)
    op.create_index('ix_laboratories_visibility', 'laboratories', ['visibility'], unique=False)
    op.create_index('ix_learning_tools_full_name', 'learning_tools', ['full_name'], unique=False)
    op.create_index('ix_learning_tools_name', 'learning_tools', ['name'], unique=False)
    op.create_index('ix_lt_users_login', 'lt_users', ['login'], unique=False)
    op.create_index('ix_permissions2lt_accessible', 'permissions2lt', ['accessible'], unique=False)
    op.create_index('ix_permissions2lt_local_identifier', 'permissions2lt', ['local_identifier'], unique=False)
    op.create_index('ix_permissions2ltuser_lt_user_id', 'permissions2ltuser', ['lt_user_id'], unique=False)
    op.create_index('ix_permissions2ltuser_permission_to_lt_id', 'permissions2ltuser', ['permission_to_lt_id'], unique=False)
    op.create_index('ix_request_permissions_lt_accessible', 'request_permissions_lt', ['accessible'], unique=False)
    op.create_index('ix_request_permissions_lt_local_identifier', 'request_permissions_lt', ['local_identifier'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_request_permissions_lt_local_identifier', table_name='request_permissions_lt')
    op.drop_index('ix_request_permissions_lt_accessible', table_name='request_permissions_lt')
    op.drop_index('ix_permissions2ltuser_permission_to_lt_id', table_name='permissions2ltuser')
    op.drop_index('ix_permissions2ltuser_lt_user_id', table_name='permissions2ltuser')
    op.drop_index('ix_permissions2lt_local_identifier', table_name='permissions2lt')
    op.drop_index('ix_permissions2lt_accessible', table_name='permissions2lt')
    op.drop_index('ix_lt_users_login', table_name='lt_users')
    op.drop_index('ix_learning_tools_name', table_name='learning_tools')
    op.drop_index('ix_learning_tools_full_name', table_name='learning_tools')
    op.drop_index('ix_laboratories_visibility', table_name='laboratories')
    op.drop_index('ix_laboratories_publicly_available', table_name='laboratories')
    op.drop_index('ix_laboratories_available', table_name='laboratories')
    ### end Alembic commands ###
