"""Added EmbedApplication etc

Revision ID: 5623247d3b03
Revises: f2b0984f780
Create Date: 2016-10-24 10:49:07.682063

"""

# revision identifiers, used by Alembic.
revision = '5623247d3b03'
down_revision = 'f2b0984f780'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GoLabOAuthUsers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.Unicode(length=255), nullable=False),
    sa.Column('email', sa.Unicode(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_GoLabOAuthUsers_display_name', 'GoLabOAuthUsers', ['display_name'], unique=False)
    op.create_index(u'ix_GoLabOAuthUsers_email', 'GoLabOAuthUsers', ['email'], unique=True)
    op.create_table('EmbedApplications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Unicode(length=255), nullable=False),
    sa.Column('name', sa.Unicode(length=100), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('scale', sa.Integer(), nullable=True),
    sa.Column('identifier', sa.Unicode(length=36), nullable=False),
    sa.Column('creation', sa.DateTime(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['GoLabOAuthUsers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_EmbedApplications_creation', 'EmbedApplications', ['creation'], unique=False)
    op.create_index(u'ix_EmbedApplications_identifier', 'EmbedApplications', ['identifier'], unique=True)
    op.create_index(u'ix_EmbedApplications_last_update', 'EmbedApplications', ['last_update'], unique=False)
    op.create_index(u'ix_EmbedApplications_name', 'EmbedApplications', ['name'], unique=False)
    op.create_index(u'ix_EmbedApplications_url', 'EmbedApplications', ['url'], unique=False)
    op.create_table('EmbedApplicationTranslation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('embed_application_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.Unicode(length=255), nullable=False),
    sa.Column('language', sa.Unicode(length=10), nullable=False),
    sa.ForeignKeyConstraint(['embed_application_id'], ['EmbedApplications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_EmbedApplicationTranslation_language', 'EmbedApplicationTranslation', ['language'], unique=False)
    op.create_index(u'ix_EmbedApplicationTranslation_url', 'EmbedApplicationTranslation', ['url'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_EmbedApplicationTranslation_url', table_name='EmbedApplicationTranslation')
    op.drop_index(u'ix_EmbedApplicationTranslation_language', table_name='EmbedApplicationTranslation')
    op.drop_table('EmbedApplicationTranslation')
    op.drop_index(u'ix_EmbedApplications_url', table_name='EmbedApplications')
    op.drop_index(u'ix_EmbedApplications_name', table_name='EmbedApplications')
    op.drop_index(u'ix_EmbedApplications_last_update', table_name='EmbedApplications')
    op.drop_index(u'ix_EmbedApplications_identifier', table_name='EmbedApplications')
    op.drop_index(u'ix_EmbedApplications_creation', table_name='EmbedApplications')
    op.drop_table('EmbedApplications')
    op.drop_index(u'ix_GoLabOAuthUsers_email', table_name='GoLabOAuthUsers')
    op.drop_index(u'ix_GoLabOAuthUsers_display_name', table_name='GoLabOAuthUsers')
    op.drop_table('GoLabOAuthUsers')
    ### end Alembic commands ###
