"""Add local time

Revision ID: 56d38b1172f9
Revises: 3999a40ec7b
Create Date: 2017-06-09 19:31:20.999843

"""

# revision identifiers, used by Alembic.
revision = '56d38b1172f9'
down_revision = '3999a40ec7b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UseLogs', sa.Column('local_date', sa.Date(), nullable=False))
    op.add_column('UseLogs', sa.Column('local_day_of_week', sa.Integer(), nullable=False))
    op.add_column('UseLogs', sa.Column('local_hour_of_day', sa.Integer(), nullable=False))
    op.add_column('UseLogs', sa.Column('local_month', sa.Integer(), nullable=False))
    op.add_column('UseLogs', sa.Column('local_year', sa.Integer(), nullable=False))
    op.create_index(u'ix_UseLogs_local_date', 'UseLogs', ['local_date'], unique=False)
    op.create_index(u'ix_UseLogs_local_day_of_week', 'UseLogs', ['local_day_of_week'], unique=False)
    op.create_index(u'ix_UseLogs_local_hour_of_day', 'UseLogs', ['local_hour_of_day'], unique=False)
    op.create_index(u'ix_UseLogs_local_month', 'UseLogs', ['local_month'], unique=False)
    op.create_index(u'ix_UseLogs_local_year', 'UseLogs', ['local_year'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_UseLogs_local_year', table_name='UseLogs')
    op.drop_index(u'ix_UseLogs_local_month', table_name='UseLogs')
    op.drop_index(u'ix_UseLogs_local_hour_of_day', table_name='UseLogs')
    op.drop_index(u'ix_UseLogs_local_day_of_week', table_name='UseLogs')
    op.drop_index(u'ix_UseLogs_local_date', table_name='UseLogs')
    op.drop_column('UseLogs', 'local_year')
    op.drop_column('UseLogs', 'local_month')
    op.drop_column('UseLogs', 'local_hour_of_day')
    op.drop_column('UseLogs', 'local_day_of_week')
    op.drop_column('UseLogs', 'local_date')
    ### end Alembic commands ###
