"""Add unsupported https url list

Revision ID: 58abc4899824
Revises: 3812c222917d
Create Date: 2019-02-24 18:35:34.484088

"""

# revision identifiers, used by Alembic.
revision = '58abc4899824'
down_revision = '3812c222917d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('HttpsUnsupportedUrls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Unicode(length=100), nullable=False),
    sa.Column('creation', sa.DateTime(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index(u'ix_HttpsUnsupportedUrls_creation', 'HttpsUnsupportedUrls', ['creation'], unique=False)
    op.create_index(u'ix_HttpsUnsupportedUrls_last_update', 'HttpsUnsupportedUrls', ['last_update'], unique=False)
    op.create_index(u'ix_HttpsUnsupportedUrls_url', 'HttpsUnsupportedUrls', ['url'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_HttpsUnsupportedUrls_url', table_name='HttpsUnsupportedUrls')
    op.drop_index(u'ix_HttpsUnsupportedUrls_last_update', table_name='HttpsUnsupportedUrls')
    op.drop_index(u'ix_HttpsUnsupportedUrls_creation', table_name='HttpsUnsupportedUrls')
    op.drop_table('HttpsUnsupportedUrls')
    ### end Alembic commands ###
