"""Add ManualApps and AllowedHost

Revision ID: 76668d91d087
Revises: 2b963e6ca2a2
Create Date: 2018-02-19 18:03:28.009222

"""

# revision identifiers, used by Alembic.
revision = '76668d91d087'
down_revision = '2b963e6ca2a2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AllowedHosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Unicode(length=100), nullable=False),
    sa.Column('creation', sa.DateTime(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_AllowedHosts_creation', 'AllowedHosts', ['creation'], unique=False)
    op.create_index(u'ix_AllowedHosts_last_update', 'AllowedHosts', ['last_update'], unique=False)
    op.create_index(u'ix_AllowedHosts_url', 'AllowedHosts', ['url'], unique=False)
    op.create_table('ManualApplications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=100), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('identifier', sa.Unicode(length=36), nullable=False),
    sa.Column('creation', sa.DateTime(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['GoLabOAuthUsers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_ManualApplications_creation', 'ManualApplications', ['creation'], unique=False)
    op.create_index(u'ix_ManualApplications_identifier', 'ManualApplications', ['identifier'], unique=True)
    op.create_index(u'ix_ManualApplications_last_update', 'ManualApplications', ['last_update'], unique=False)
    op.create_index(u'ix_ManualApplications_name', 'ManualApplications', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_ManualApplications_name', table_name='ManualApplications')
    op.drop_index(u'ix_ManualApplications_last_update', table_name='ManualApplications')
    op.drop_index(u'ix_ManualApplications_identifier', table_name='ManualApplications')
    op.drop_index(u'ix_ManualApplications_creation', table_name='ManualApplications')
    op.drop_table('ManualApplications')
    op.drop_index(u'ix_AllowedHosts_url', table_name='AllowedHosts')
    op.drop_index(u'ix_AllowedHosts_last_update', table_name='AllowedHosts')
    op.drop_index(u'ix_AllowedHosts_creation', table_name='AllowedHosts')
    op.drop_table('AllowedHosts')
    # ### end Alembic commands ###
