"""Add default_autoload to RLMS

Revision ID: 7f806cb0445
Revises: 1c131a5ca91f
Create Date: 2014-12-04 11:44:28.965502

"""

# revision identifiers, used by Alembic.
revision = '7f806cb0445'
down_revision = '1c131a5ca91f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rlmss', sa.Column('default_autoload', sa.Boolean(), nullable=True))
    op.create_index('ix_rlmss_default_autoload', 'rlmss', ['default_autoload'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rlmss_default_autoload', table_name='rlmss')
    op.drop_column('rlmss', 'default_autoload')
    ### end Alembic commands ###
