"""add new column to go lab booking system

Revision ID: c1a931faf5f
Revises: 551dcad9db25
Create Date: 2014-08-26 11:00:07.140731

"""

# revision identifiers, used by Alembic.
revision = 'c1a931faf5f'
down_revision = '551dcad9db25'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laboratories', sa.Column('go_lab_reservation', sa.Boolean(), nullable=False))
    op.create_index('ix_laboratories_go_lab_reservation', 'laboratories', ['go_lab_reservation'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_laboratories_go_lab_reservation', table_name='laboratories')
    op.drop_column('laboratories', 'go_lab_reservation')
    ### end Alembic commands ###
